language: generic 
services:
  - docker

before_install:
  - docker build -t emirhamidovic/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true emirhamidovic/react-test npm test

after_success:
  - docker build -t emirhamidovic/multi-client ./client
  - docker build -t emirhamidovic/multi-nginx ./nginx
  - docker build -t emirhamidovic/multi-server ./server
  - docker build -t emirhamidovic/multi-worker ./worker 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-std-in
  - docker push emirhamidovic/multi-client
  - docker push emirhamidovic/multi-nginx
  - docker push emirhamidovic/multi-server
  - docker push emirhamidovic/multi-worker